FROM gradle:8.1.1-jdk11 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src

FROM openjdk:11-jre-slim
COPY --from=build /home/gradle/src/build/libs/albumsService-0.0.1-SNAPSHOT.jar AlbumsService.jar
ENTRYPOINT ["java","-jar","AlbumsService.jar"]