FROM gradle:8.1.1-jdk11 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src

FROM openjdk:11-jre-slim
COPY /src/main/resources/security/apiEncryptionKey.jks apiEncryptionKey.jks
COPY --from=build /home/gradle/src/build/libs/configServer-0.0.1-SNAPSHOT.jar ConfigServer.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","ConfigServer.jar"]